### ISSUE TITLE
redisq delete message does not support ZRem

### ISSUE THREAD

**Issue by togettoyou** [vmihailenco/taskq#104]
I want to add a message to the queue, and Delay is greater than 0
![image](https://user-images.githubusercontent.com/55381228/105438872-d0a51500-5c9e-11eb-9edf-ad0a6ec182d8.png)

Now I want to delete this message, but your delete default is XDel
![image](https://user-images.githubusercontent.com/55381228/105439009-0813c180-5c9f-11eb-829c-76a2214e2a20.png)

**Comment by rbg** [comment]
@vmihailenco looks like a bug :)

**Comment by vmihailenco** [comment]
`Delete` is an internal API for this package. It is only used by `Consumer` and is not exported to users.

I guess the answer is that deleting messages is not supported.

**Comment by togettoyou** [comment]
thank you. However, if I want to set a delayed task, is it impossible to delete it?

**Comment by togettoyou** [comment]
@vmihailenco

**Comment by vmihailenco** [comment]
>thank you. However, if I want to set a delayed task, is it impossible to delete it?

Yes, it is not supported.

Technically nothing prevents you from calling `q.redis.ZRem(msg.Ctx, q.zset, body)` manually....
