### ISSUE TITLE
should create a peridic job to clean zoombie consumer

### ISSUE THREAD

**Issue by lilien1010** [vmihailenco/taskq#116]
```
**:6379> xinfo consumers company  cg1
1) 1) "name"
   2) "c1"
   3) "pending"
   4) (integer) 3
   5) "idle"
   6) (integer) 4785470
```
once the idle is longer than a duration(6 hours maybe), we should del this consumer。

Once a consumer was killed unexpectedly, that consumer will be left as an Orphan.

**Comment by vmihailenco** [comment]
Perhaps - I don't have any production experience with Redis Queue. I would expect it to delete dead consumers, but I really don't have an idea...

There are some background jobs already - see https://github.com/vmihailenco/taskq/blob/v3/redisq/queue.go#L91-L101. You could add another one that would poll Redis as needed.
