### ISSUE TITLE
Lack of CHANGELOG.md file

### ISSUE THREAD

**Issue by lilien1010** [vmihailenco/taskq#125]
in the lastest 3.2.5 release, the release log is `check the CHANGELOG.md xxx` 
![image](https://user-images.githubusercontent.com/3814966/132129768-58b14cba-ad7a-4385-9629-5d595b09801f.png)

but there is no CHANGELOG.md in the repo

**Comment by vmihailenco** [comment]
There are 2 options:
- change the message to something like "Check commits for details"
- start maintaining a changelog

Which do you prefer?

**Comment by lilien1010** [comment]
I'd like to maintain a CHANGELOG.md in the repo,
like [this](https://github.com/apache/apisix/blob/master/CHANGELOG.md)

**Comment by vmihailenco** [comment]
Me too, but I never had enough discipline to do it :) It looks like https://www.conventionalcommits.org/en/v1.0.0/ and some tool to generate a changelog. Do you have any experience with setting up the build for such workflow?

**Comment by lilien1010** [comment]
I don't have that  experience either, But we can try to start with some workflow by learning from other projects.

**Comment by vmihailenco** [comment]
Do you have a good example of Go projects that use conv commits with Git hooks? So far I've only seen JS projects, but they require package.json file...

**Comment by lilien1010** [comment]
no sure this is what you want 
https://github.com/marketplace/actions/auto-generate-changelog

**Comment by vmihailenco** [comment]
Yep, that is useful - thanks. But what is missing is something like https://typicode.github.io/husky/#/ - commit linter that does not require JS (or some way to use husky with Go projects).

**Comment by vmihailenco** [comment]
Changelog should be auto-generated with commitlint - see https://github.com/vmihailenco/taskq/pull/138/commits/22e4d67d4b85ac47935a00b13f0d2a9e270d25a3. Closing.
