### ISSUE TITLE
Maybe Millisecond??

### ISSUE THREAD

**Issue by yedemon** [vmihailenco/taskq#151]
in redisq/queue.go 
func cleanZombieConsumers

line 382: if time.Duration(consumer.Idle)*time.Second > q.opt.ConsumerIdleTimeout {

Maybe it is time.Millisecond ?

Sorry if i am wrong, just want to help. =w=

**Comment by vmihailenco** [comment]
You are right. We should use `time.Millisecond` in taskq and improve go-redis to use `time.Duration` instead of `int64`.

Could you send a PR?

**Comment by yedemon** [comment]
Thanks for inviting. It's the first time to do a pull request. let'me try..

**Comment by yedemon** [comment]
Oh, I think i've made a pr now. Hope it's right :) ..
