### ISSUE TITLE
Can't pass multiple arguments to the task handler

### ISSUE THREAD

**Issue by gustavoaborges** [vmihailenco/taskq#155]
I can't seem to be able to pass multiple arguments to a Task's handler function 

When calling like `tasks.MainQueue.Add(tasks.CountTask.WithArgs(context.Background(), "hello", "example", "test"))` I can't retrieve all the 3 arguments on the handler

```go
CountTask = taskq.RegisterTask(&taskq.TaskOptions{
		Name: "counter",
		Handler: func(arg1, arg2, arg3 string) error {
			println("handler:", arg1, arg2, arg3)
			IncrLocalCounter()
			return nil
		},
	})
```
I get `consumer.go:616: task="counter" failed (will retry=1 in dur=30s): taskq: got 1 args, wanted 3`

When I try

```go
CountTask = taskq.RegisterTask(&taskq.TaskOptions{
		Name: "counter",
		Handler: func(arg1 *taskq.Message) error {
			println("handler:", arg1.Args)
			IncrLocalCounter()
			return nil
		},
	})
```

I get an empty array `handler: [0/0]0x0`

With the handler function accepting just one string argument, it prints the last argument:
```go
CountTask = taskq.RegisterTask(&taskq.TaskOptions{
		Name: "counter",
		Handler: func(arg1 string) error {
			println("handler:", arg1)
			IncrLocalCounter()
			return nil
		},
	})
```
The output is `handler: test`

I wonder how can I pass multiple arguments to a handler function or if this is a bug

**Comment by vmihailenco** [comment]
>I get consumer.go:616: task="counter" failed (will retry=1 in dur=30s): taskq: got 1 args, wanted 3

Most likely this is an error for old messages that were already in the queue. Try to reset the queue or create a new one.
