### ISSUE TITLE
memqueue_test.go makes use of Redis

### ISSUE THREAD

**Issue by shaunco** [vmihailenco/taskq#162]
Perhaps I'm missing something obvious, but I don't see why `memqueue/memqueue_test.go` uses a Redis Ring. Given that `memqueue/queue.go` is supposed to be an entirely in-memory queue, it seems odd that the unit tests are some weird hybrid of in-memory and Redis.

**Comment by vmihailenco** [comment]
Perhaps it should not.

But it is this way, because back in the days redisq backend did not exist and I needed some way to use taskq locally without S3/SQS. So I've replaced S3 with memqueue and left Redis as is because it is easy to run Redis locally.

**Comment by shaunco** [comment]
Happy to put together a PR to remove Redis from the memqueue_test.go file if you'd be willing to consider it.

**Comment by vmihailenco** [comment]
Looks related to https://github.com/vmihailenco/taskq/pull/106? I guess we could use local storage with memqueue by default.

**Comment by shaunco** [comment]
Agreed, local storage would be the ideal fix.

**Comment by mrz1836** [comment]
Any idea when a new release will be made? Looks like there's some fixes still in the `v3` branch but not in an tagged version (yet).

Thanks!

**Comment by lilien1010** [comment]
I think we can close  https://github.com/vmihailenco/taskq/pull/163  as this is merge now :

**Comment by lzap** [comment]
Hey, I am trying to use the in-memory queue but it still appears to require redis (taskq 3.2.9):

```
		factory := memqueue.NewFactory()
		queue.JobQueue = factory.RegisterQueue(&taskq.QueueOptions{
			Name:        config.QueueName(),
			Storage:     taskq.NewLocalStorage(),
			WorkerLimit: 1,
		})
```

I am running into:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x38 pc=0x1037afb70]

goroutine 79 [running]:
github.com/bsm/redislock.(*Client).obtain(0x140002b5260, {0x10475ca20, 0x140000ac960}, {0x140001a35f0, 0x24}, {0x14000b31c68?, 0x1056c8300?}, 0x64?)
        /Volumes/SSD/Go/pkg/mod/github.com/bsm/redislock@v0.7.2/redislock.go:101 +0x50
github.com/bsm/redislock.(*Client).Obtain(0x140002b5260, {0x10475c9e8, 0x140001a4000}, {0x140001a35f0, 0x24}, 0x1037cb70c?, 0x0)
        /Volumes/SSD/Go/pkg/mod/github.com/bsm/redislock@v0.7.2/redislock.go:73 +0x1b8
github.com/bsm/redislock.Obtain({0x10475c9e8, 0x140001a4000}, {0x0?, 0x0}, {0x140001a35f0, 0x24}, 0x14000084688?, 0x102388310?)
        /Volumes/SSD/Go/pkg/mod/github.com/bsm/redislock@v0.7.2/redislock.go:129 +0x98
github.com/vmihailenco/taskq/v3.(*Consumer).lockWorker(0x1400013dc70, {0x10475c9e8, 0x140001a4000}, 0x0, 0x2101?)
        /Volumes/SSD/Go/pkg/mod/github.com/vmihailenco/taskq/v3@v3.2.9/consumer.go:720 +0x170
github.com/vmihailenco/taskq/v3.(*Consumer).worker(0x1400013dc70, {0x10475c9e8?, 0x140001a4000}, 0x0)
        /Volumes/SSD/Go/pkg/mod/github.com/vmihailenco/taskq/v3@v3.2.9/consumer.go:468 +0xd8
github.com/vmihailenco/taskq/v3.(*Consumer).addWorker.func1()
        /Volumes/SSD/Go/pkg/mod/github.com/vmihailenco/taskq/v3@v3.2.9/consumer.go:276 +0x64
created by github.com/vmihailenco/taskq/v3.(*Consumer).addWorker
        /Volumes/SSD/Go/pkg/mod/github.com/vmihailenco/taskq/v3@v3.2.9/consumer.go:274 +0x1c0
```

So I guess that is not all that needs changing :-(

Edit: It is a bug: https://github.com/vmihailenco/taskq/issues/176
