### ISSUE TITLE
How to stop a running queue at runtime??

### ISSUE THREAD

**Issue by yedemon** [vmihailenco/taskq#166]
I'm curious about how to stop a running queue without stop the programme. Becauze I've to start the queue accordingly. And can't just leave them on the floor.

Please help..

**Comment by lilien1010** [comment]
taskq.StopConsumers

**Comment by yedemon** [comment]
Oh, Sorry, I didn't make it clear.  I am asking about that "Unregister Queue" interal function. In my scenario, i have a dynamic queue to create. So when the time comes, i have to remove it completely. i have no place to record which task name have been used, and besides new Queue might be different in options. Since there is a "Unregister" function in the internal/base/factory.go, why just holding it back from these main factories, e.g. redisq/factory.go? 

Apology if this is being rude :)..
