### ISSUE TITLE
Please add q.wg.Wait() to redisq.go 

### ISSUE THREAD

**Issue by yedemon** [vmihailenco/taskq#167]
After a carefully look, I found the wg in redisq.go is used only at RunQueue(), and has no Wait calls. 

Should we add q.wg.Wait() to CloseTimeOut or some place else?? 

Because I'd really want to stop a running queue.

Please take this small quest into consideration. Thanks.. and thanks

**Comment by lilien1010** [comment]
Hi @yedemon I did some research on your question, can you setup a PR to fix it?

**Comment by yedemon** [comment]
Sure, with pleasure. Here it's.  https://github.com/vmihailenco/taskq/pull/175
