### ISSUE TITLE
Redisq Queue Scheduler Time Sleep Option

### ISSUE THREAD

**Issue by Baseris** [vmihailenco/taskq#172]
Hello, we are using taskq in long time with 17 different queue and  4GB RAM / 2vCPU redis instance. Queues are empty, but i see redis running with high cpu(80%) all time. Taskq making too much command regulary because of redisq queue scheduler() sleeping less than 500ms.
I tested time sleep for 1 sec, cpu usage down to 36%. And tested for 10sec, cpu usage down to 11%. With these options application running normaly. Is there avaible to add new option for schedulerBackoff()

**Comment by lilien1010** [comment]
@vmihailenco I  think the backoff time of scheduler can increase to 1 ~1.5 sec, WDYT

**Comment by vmihailenco** [comment]
@lilien1010 agreed, let's change the default value too.
