### ISSUE TITLE
Release function - why do we not use XCLAIM

### ISSUE THREAD

**Issue by silasdavis** [vmihailenco/taskq#40]
Thanks for the library, I was having issues with another redis queue - I didn't know about consumer groups so this looks great.

I was just looking at the message recovery code and I have a question about the `Release` function in redisq (https://github.com/vmihailenco/taskq/blob/master/redisq/queue.go#L205-L213)

You use `XDEL` to remove a timed out message the re-add it to the queue. Seems like this would usually be okay, but since it is not atomic if we were to crash during `Release` we could delete a message without re-adding it.

I was expecting to find a usage of `XCLAIM` (https://redis.io/commands/xclaim) which seems to be designed for this purpose. Is there a particular reason you did not use this? Would it be a good idea to use it?

**Comment by vmihailenco** [comment]
In Release the goal is to retry the message with some delay which I believe can't be achieved with XCLAIM. That is why the message is deleted and scheduled to be executed later using Redis set.

>Seems like this would usually be okay, but since it is not atomic if we were to crash during Release we could delete a message without re-adding it.

True, the alternative would be to first add/schedule it and then delete.

**Comment by silasdavis** [comment]
Thanks for speedy reply. I've read the code a little more to try to understand the design.

> True, the alternative would be to first add/schedule it and then delete.
Then I suppose we may double process a task, perhaps we can say this is less likely given we think we have detected the failure of the consumer we are stealing messages from. Would still be nice to avoid.

Firstly can we just wrap them in a transaction with a `MULTI` to make it atomic (or seems like maybe Pipeline is the way to do this)?

I see that you use a zset to maintain a list of messages sorted by their minimum start time. With release you want to respect the delay set previously. This seems like a nice design, but another option would be to store an absolute minimum start time (rather than relative delay) with the message itself and just re-queue it it is received before its allotted start time. The downside of this is the write churn it creates on the queue for no good reason, so I prefer the current design really.

**Comment by silasdavis** [comment]
I had a go at using a transaction here: https://github.com/vmihailenco/taskq/pull/41

**Comment by silasdavis** [comment]
fixed in #41
