### ISSUE TITLE
Option to not use global registry

### ISSUE THREAD

**Issue by silasdavis** [vmihailenco/taskq#45]
I have dispatcher type with some internal state. The dispatcher is passed to my worker orchestrator 'workers', workers then calls `Init()` on the dispatcher. This registers the tasks and dispatcher holds a reference to them. The state in the dispatcher is local, but it is closed into the handler functions which are global, which is the cause of my issue.

I could work around this by implementing a namespace for task names, with a prefix for instance. But it would be cleaner if I could just use a separate registry for each queue/consumer.

How would you feel about having `Queue` hold a reference to a registry? I propose we:

- Export the `TaskRegistry` type
- Add `Tasks *TaskRegistry` to `QueueOptions`
- Default the `Registry` to be global `Tasks`

Will submit PR if you agree.

**Comment by vmihailenco** [comment]
I can't say I fully understand the problem from your description so instead I will explain my current understanding of this topic. Please note that the v2 is still in beta so nothing is final yet.

So few weeks ago each queue had a separate task registry and tasks were created using `mytask := myqueue.RegisterTask(...)`. And later you could use only task to add a message to the queue, e.g. `mytask.Call(arg1, arg2, arg3)` adds a message with args to the queue `myqueue`. That worked fine but:
- Task was coupled with the queue so the queue must be created before the task. That is Inconvenient when you want to share single queue between multiple packages, e.g. have `mainQueue` definited somewhere.
- You can't add same task to multiple queues, e.g. you can't do `shard1Queue.Add(myTask)` and `shard2Queue.Add(myTask)`. You need a separate task for each queue.
- You can't freely move tasks between packages / queues.

Single global registry decoupled from queues solves all of that. Tasks can be created without queues, moved from one package to another, added to multiple queues etc.

>Export the TaskRegistry type
>Add Tasks *TaskRegistry to QueueOptions
>Default the Registry to be global Tasks

This sounds harmless enough. You probably also need to change RegisterTask to actually register task in your registry. Probably it should be `CustomTaskRegistry.Register(*TaskOptions)` with global `RegisterTask` changed to:

```go
func RegisterTask(opt *TaskOptions) *Task {
  return Tasks.Register(opt)
}
```

Hard to say where that leads us but it looks good enough on paper.

**Comment by silasdavis** [comment]
>I can't say I fully understand the problem from your description

Sorry I wasn't very clear, some code might help, I have the following:

```go
func NewDispatcher(queue taskq.Queue, handlers *Handlers, params *Params) *Dispatcher {
	if handlers.ErrorReporter == nil {
		handlers.ErrorReporter = func(error) {}
	}
	return &Dispatcher{
		queue:  queue,
		params: params,

		signupTokenEmail: registerTask(params,
			"SignupTokenEmail",
			handlers.SignupTokenEmail,
			func(emailAddress string) {
				handlers.ErrorReporter(fmt.Errorf("could not send signup token email to %s", emailAddress))
			}),

		passwordResetEmail: registerTask(params,
			"PasswordResetEmail",
			handlers.PasswordResetEmail,
			func(accountID int) {
				handlers.ErrorReporter(fmt.Errorf("could not send password reset email for account %d", accountID))
			}),
	}
}

func registerTask(params *Params, name string, handler interface{}, fallbackHandler interface{}) *taskq.Task {
	return taskq.RegisterTask(&taskq.TaskOptions{
		Name:            name,
		Handler:         handler,
		FallbackHandler: fallbackHandler,
		MinBackoff:      params.MinBackoff,
		MaxBackoff:      params.MaxBackoff,
		RetryLimit:      params.RetryLimit,
		DeferFunc:       params.DeferFunc,
	})
}
```

If I make a second `Dispatcher` - even on a different queue then the current code will panic on `registerTask`

I definitely see why you changed it to give tasks independence from the queue that makes a lot of sense. It seems like we could have the best of both worlds - avoid global state where it is problematic but still have task/registries as independent. I'll work something through and we can see how it ends up...
