### ISSUE TITLE
Add ability to disable autotuner

### ISSUE THREAD

**Issue by vmihailenco** [vmihailenco/taskq#49]
Currently taskq consumer starts with 1 fetcher and 1 worker. Then it automatically adds and removes fetchers and workers based on the current load. It usually works fine but it is not very well tested. So there should be an ability to disable this behavior.

/cc @silasdavis just in case it affects you. This is recent v2 addition and I am not sure how it performs on different workloads...

**Comment by silasdavis** [comment]
Thanks, came across that, looked interesting. Will take a closer look.

**Comment by vmihailenco** [comment]
Setting `MinNumWorker >= MaxNumWorker` disables new "autotuner" in v3 - closing.
