### ISSUE TITLE
Ability to provide generic fallback handler

### ISSUE THREAD

**Issue by silasdavis** [vmihailenco/taskq#50]
Currently the fallback handler is passed through the same handle machinery as the normal handler. This makes sense when you want to take a task-specific fallback action, but when you just wan to log or alert on the message in a generic way it is slightly onerous to write a custom fallback handler that basically does the same thing - in my case log the task and arguments to an error reporter. If I didn't have to match the type and number of arguments of the message I could just reuse the same implementation.

To support this `fnArgs` could accept a certain function signature regardless of the shape of the message. The two candidates I can think of are:

```go
func(context.Context, args... interface{})
```
or:
```go
func(context.Context, msg *Message)
```
modulo the `Context` obviously

I think I prefer the second because it makes other potentially useful information available like the message `Name` and the `ReservedCount`.

It might make sense to allow handlers too to take a single `Message` argument - where they too could also potentially benefit from the metadata or possibly be defined generically.

The implementation of this would be very simple - if there is a single `Message` arg then just pass that. However I think there may be an issue with the message compression whereby the `Args` field is not necessarily filled - what would be the best strategy here?

**Comment by silasdavis** [comment]
Oh I also noticed that `func()` works for fallbackHandler for a message with non-zero args provided `Args` has not been initialised on the message. This seems more like an accident than by design, but I could be wrong.

**Comment by vmihailenco** [comment]
`func ()`, `func (*Message)`, and `func (context.Context, *Message)` should already work for all handlers and you can rely on this behavior. `func ()` support should be coded more explicitly, but I already use this behavior in few places.

**Comment by vmihailenco** [comment]
See https://github.com/vmihailenco/taskq/blob/master/handler.go#L38-L70 for all the invariants

**Comment by silasdavis** [comment]
Ah hah, brilliant!
