### ISSUE TITLE
version 2.1.2 has a dependency of 1.8.2 which is incorrectly using using an internal package

### ISSUE THREAD

**Issue by rodrabe** [vmihailenco/taskq#54]
I am getting this error when I am asking for 2.1.2:

../../../../pkg/mod/github.com/vmihailenco/taskq@v1.8.2/message.go:10:2: use of internal package github.com/go-msgqueue/msgqueue/internal not allowed

Is there a way to break that dependency?

Thanks for responding to my previous issue.

**Comment by vmihailenco** [comment]
v2 requires Go modules support see not in the readme - https://github.com/vmihailenco/taskq#installation
