### ISSUE TITLE
undefined: syscall.Sysinfo_t

### ISSUE THREAD

**Issue by ClayShentrup** [vmihailenco/taskq#58]
```
# github.com/capnm/sysinfo
vendor/github.com/capnm/sysinfo/sysinfo.go:62:9: undefined: syscall.Sysinfo_t
vendor/github.com/capnm/sysinfo/sysinfo.go:65:9: undefined: syscall.Sysinfo
```

**Comment by vmihailenco** [comment]
Wrong repo?

**Comment by ClayShentrup** [comment]
Is this not a dependency of yours? How is it working for you and not me unless this is something like a failure to pin a version correctly or something like that?

**Comment by vmihailenco** [comment]
You are right - it is a dependency.

**Comment by ClayShentrup** [comment]
So is this some kind of version drift issue? I mean, clearly it's working for you.

**Comment by vmihailenco** [comment]
github.com/capnm/sysinfo is a Linux syscall - I guess you are not using Linux.
