### ISSUE TITLE
Dynamic BufferSize or Consumer.Add() spawns a goroutine?

### ISSUE THREAD

**Issue by shaunco** [vmihailenco/taskq#63]
The current BufferSize implementation in queue.go makes it so that if a task is added to the queue and the queue is full, the AddTask call will block until a task completes. This has caused me issues in two cases:

Two different tasks in two different queues might add work to each other, and as soon as buffer size is exceeded, you end up in a deadlock where taskA.handler is calling queueB.Add() and taskB.handler is calling queueA.Add(). Sure, I can keep upping BufferSize, but there are cases like packet processing the number of queued tasks is beyond a developer's control.

Similarly, if a queue is full and one of the tasks in that queue tries to add another task to the queue, the calling task becomes deadlocked. There are plenty of instances where you might have something like PreprocessTask and PostprocessTask in the same queue and when Preprocess finishes, it queues Postprocess.

I've attached some code that demonstrates these two.

It seems like there are two possible fixes, but I haven't fully wrapped my head around the entire taskq package enough to submit a PR. It would seem that either adding a dynamic BufferSize that isn't tied to ReservationSize would fix this, or having Consumer.Add() do the channel send in a goroutine:

```go
func (c *Consumer) Add(msg *Message) error {
	_ = c.limiter.Reserve(msg.Ctx, 1)	
	go func() {
		c.buffer <- msg
	}()
	return nil
}
```
... which keeps BufferSize as is, but at the overhead of spawning goroutines.

[taskqchaos.zip](https://github.com/vmihailenco/taskq/files/4534573/taskqchaos.zip)

**Comment by vmihailenco** [comment]
Typically consumer and producer are run in separate processes so this problem does not exist. Perhaps you can do the same...

> having Consumer.Add() do the channel send in a goroutine

Can't you instead call `Add` in a goroutine like `go q.Add(msg)` or `go q.Call(...)`?

> dynamic BufferSize that isn't tied to ReservationSize

BufferSize is not tied to ReservationSize - you can specify whatever value you like.

**Comment by shaunco** [comment]
Fair on all points... not sure how I didn't think to call add in a goroutine (doh!).
