### ISSUE TITLE
Unable to grep the package

### ISSUE THREAD

**Issue by kushthedude** [vmihailenco/taskq#66]
#### Description

Running `go get github.com/vmihailenco/taskq/v3` gives the error due to go-redis .

#### Error Trace:-
```sh
go: github.com/vmihailenco/taskq/v3@v3.0.0-beta.8 requires
5
	github.com/go-redis/redis/v8@v8.0.0-alpha.1: reading github.com/go-redis/redis/go.mod at revision v8.0.0-alpha.1: unknown revision v8.0.0-alpha.1
6
##[error]Process completed with exit code 1.
```

**Comment by kushthedude** [comment]
cc: @vmihailenco @silasdavis

**Comment by vmihailenco** [comment]
Thats my fault - I accidentally messed up with tags form go-redis v8 alpha branch. Try re-installing and the issue should be fixed.

**Comment by kushthedude** [comment]
Hey @vmihailenco, still facing the issue
```sh
go: github.com/vmihailenco/taskq/v3@v3.0.0-beta.9 requires
5
	github.com/go-redis/redis_rate/v9@v9.0.0-alpha.4 requires
6
	github.com/go-redis/redis/v8@v8.0.0-alpha.0: reading github.com/go-redis/redis/go.mod at revision v8.0.0-alpha.0: unknown revision v8.0.0-alpha.0
```

**Comment by vmihailenco** [comment]
Did you try `go get -u`?

**Comment by kushthedude** [comment]
> Did you try `go get -u`?

Yes same issue, also the CI is failing checks due to the same error.

**Comment by kushthedude** [comment]
Hey @vmihailenco , Specifying the master branch did the trick. Can you make a new release for these changes?

**Comment by vmihailenco** [comment]
Done
